name: Build and Release
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y make cmake autoconf automake build-essential ninja-build libssl-dev libuv1-dev libnghttp2-dev libtool libcap-dev

      - name: Checkout Repository (liboqs)
        uses: actions/checkout@v3
        with:
          repository: open-quantum-safe/liboqs
          ref: af76ca3b1f2fbc1f4f0967595f3bb07692fb3d82
          path: liboqs

      - name: Checkout Repository (pqc-openssl)
        uses: actions/checkout@v3
        with:
          repository: nirajsapkota/pqc-openssl
          path: pqc-openssl

      - name: Checkout Repository (pqc-bind)
        uses: actions/checkout@v3
        with:
          path: pqc-bind
          fetch-depth: 0

      - name: Build (liboqs)
        run: |
          mkdir /home/runner/work/pqc-bind/pqc-bind/liboqs/build
          cd /home/runner/work/pqc-bind/pqc-bind/liboqs/build
          cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/runner/work/pqc-bind/pqc-bind/pqc-openssl/oqs ..
          sudo ninja
          sudo ninja install

      - name: Build (pqc-openssl)
        run: |
          cd /home/runner/work/pqc-bind/pqc-bind/pqc-openssl
          ./Configure no-shared linux-x86_64 --prefix=/home/runner/work/pqc-bind/pqc-bind/pqc-openssl-build -lm
          sudo make
          sudo make install

      - name: Build (pqc-bind)
        run: |
          cd /home/runner/work/pqc-bind/pqc-bind/pqc-bind
          autoreconf -fi
          ./configure CFLAGS="-Wl,--no-as-needed" LIBS="-loqs -ldl" CPPFLAGS="-I/home/runner/work/pqc-bind/pqc-bind/pqc-openssl/oqs/include" LDFLAGS="-L/home/runner/work/pqc-bind/pqc-bind/pqc-openssl-build/lib -L/home/runner/work/pqc-bind/pqc-bind/pqc-openssl/oqs/lib" --with-openssl=/home/runner/work/pqc-bind/pqc-bind/pqc-openssl --prefix=/home/runner/work/pqc-bind/pqc-bind/pqc-bind-build --sysconfdir=/etc
          sudo make
          sudo make install

      - name: Package
        run: |
          cd /home/runner/work/pqc-bind/pqc-bind/pqc-bind-build
          sudo zip -r release.zip .

      - name: Get Latest Git Tag
        id: get-tag
        run: |
          cd /home/runner/work/pqc-bind/pqc-bind/pqc-bind
          tag=$(git describe --abbrev=0 --tags || echo "v0.0.0")
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Generate Version
        id: version
        run: |
          tag="${{ steps.get-tag.outputs.tag }}"
          versionParts=(${tag//./ })
          newVersion="${versionParts[0]}.${versionParts[1]}.$((${versionParts[2]}+1))"
          echo "version=${newVersion}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Release notes for version ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /home/runner/work/pqc-bind/pqc-bind/pqc-bind-build/release.zip
          asset_name: pqc-bind.zip
          asset_content_type: application/zip
